spring.datasource.url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username: ${DB_USERNAME:postgres}
spring.datasource.password: ${DB_PASSWORD:example}
spring.datasource.driver-class-name: org.postgresql.Driver
spring:
  jpa:
    hibernate:
      ddl-auto: create